---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/events":
    get:
      summary: list events
      responses:
        '200':
          description: successful
    post:
      summary: create event
      responses:
        '200':
          description: successful
  "/events/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show event
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000/
