default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: timely_backend_development
  username: ubuntu
  password: athika123

test:
  <<: *default
  database: timely_backend_test
  username: ubuntu
  password: athika123

production:
  <<: *default
  database: timely_backend_production
  username: <%= ENV["TIMELY_BACKEND_DATABASE_USER"] %>
  password: <%= ENV["TIMELY_BACKEND_DATABASE_PASSWORD"] %>
  host: <%= ENV["TIMELY_BACKEND_DATABASE_HOST"] %>
  port: <%= ENV["TIMELY_BACKEND_DATABASE_PORT"] %>
